# WARNING: This file is managed automatically and may be overwritten at any time.

name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  Commit:
    uses: schubergphilis-ep/github-terraform-workflows/.github/workflows/commit.yaml@v2.0.0
    permissions:
      contents: read
      pull-requests: write
    secrets: inherit

  Provider:
    uses: schubergphilis-ep/github-terraform-workflows/.github/workflows/provider-ci.yaml@v2.0.0
    permissions:
      contents: read
    secrets: inherit
